language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: "Tp5mSrs1EbgJgIYd/aIBNIn04qUYgN2GqfHaFyELhQyzGSVeReBo51Cnp3tzqCwLne66Zm0MeVvrOP6fe2e9PBPGipbIRTXQXs66nJv/4+yOX5AohX92JbpUiNO1Ckovl8B2tpXC4/qr2otl7SGZgxVjxmdUvo0g0DuU+cfo3lV6cuBlgCR7x+ws+qMYDu/04Fw5/pZrnsJgsA+DdHCf8dUdL0vB+nMdoDYKRixtM9RLh5gqEKbXxn/VFM8QQF+o37gc/8lgH5LwPw+/NvC59ED93q5kNH8Nj/Ht33j1dQu5Dqu31vE8YMX0kSbRc7qxSLiiFPrE+RQrzP74i+Mu50WM0QAcCtiefVBRb+LWx4QoMyC197pev9k1wgOneHe8B0xKR0jeazsoSA3/kA2enQ/vtBO3tWIpFwDgjZAK1toPZTZCXvl7Wy11Qt0ryDvfHejpZbrz9M0LZ33XK9ndZo64JZvnFqgT/L8rWTlMpTKKHWmyFrOSqI4mYrYsn5oi7hQLsYDKPiDtBLHvmVVlRmRvnA+2l1s1wtnndZK4MpKebco2auzDAqJfp8BJopTxcuGp0XdxHK/PHqZA5AudC3G8hlkXoWbhqUUzX48sGaU/o9QtKfDPdjUwoiW212kGmKyDkr+4AXiZGrdY3CsufjwwoRwJiZ6NjFj/xXQUUdw="
  api_key:
    secure: oYcPdAZMGsM2SMFgexo3OybOt/8Uq32NJJAkGcdxzaRgOY2hI8yn389ceU+7MHBGkvLJfRECDq3s4egba4OTEPI20bYGk9kksw6JwfHcmrE6Ag0zWYzqy7KwyavEyF4qhAmv2hV8Wd82rTA2+LX7jQT/KZ1A2lcpFTrVo/3KsyNVUn42yV010QlLrPPbEFbeYpqAz2hKAqJ6FhCF9VPVPRdzFhfe/7b83ch8wGIAs2qxJygd7UvnIn5pBmbhXtl6ePEt/B5lNlm0EvDBFtWwlxDLC8WIktZTSrHsPhlEvsza61D5va7Q12Xi28v0FtsqpNWqg9w+xUF4EYq61FOAxjrCrPTz0/qzanN1Pykehd6Ee37l1zPzyyDl0cJXy7MBf7n7ErxyKaX/DSfYnC1Gq6T/nc16grZRAC7mD5hswBbNvNKMl7lTO8BEovguJnmTD62kiVmxWOg9mrYG+gw/TBQocJYRb4lhIcZV7ateNAZq0ABGoAL9x+ZswO6E2vi/lCuGbJYQpwUI5jeMDEaGU1qkhiNnb0B7uCVYWBEZGaYWpvlFtU0OO3YwcpBW53dUL16BmjbigPCnxRjIE4o4OVcLr95ujUTSFw2iogZ4ujgo8Rcmx46xexYKS/3qMH4DxjvZJokvbsTIYF2D0Jzfq5gg3F8BBTGViW9+7A9w8uA=
  on:
    tags: true
    repo: ajulienne/tartiflette
