language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: Tp5mSrs1EbgJgIYd/aIBNIn04qUYgN2GqfHaFyELhQyzGSVeReBo51Cnp3tzqCwLne66Zm0MeVvrOP6fe2e9PBPGipbIRTXQXs66nJv/4+yOX5AohX92JbpUiNO1Ckovl8B2tpXC4/qr2otl7SGZgxVjxmdUvo0g0DuU+cfo3lV6cuBlgCR7x+ws+qMYDu/04Fw5/pZrnsJgsA+DdHCf8dUdL0vB+nMdoDYKRixtM9RLh5gqEKbXxn/VFM8QQF+o37gc/8lgH5LwPw+/NvC59ED93q5kNH8Nj/Ht33j1dQu5Dqu31vE8YMX0kSbRc7qxSLiiFPrE+RQrzP74i+Mu50WM0QAcCtiefVBRb+LWx4QoMyC197pev9k1wgOneHe8B0xKR0jeazsoSA3/kA2enQ/vtBO3tWIpFwDgjZAK1toPZTZCXvl7Wy11Qt0ryDvfHejpZbrz9M0LZ33XK9ndZo64JZvnFqgT/L8rWTlMpTKKHWmyFrOSqI4mYrYsn5oi7hQLsYDKPiDtBLHvmVVlRmRvnA+2l1s1wtnndZK4MpKebco2auzDAqJfp8BJopTxcuGp0XdxHK/PHqZA5AudC3G8hlkXoWbhqUUzX48sGaU/o9QtKfDPdjUwoiW212kGmKyDkr+4AXiZGrdY3CsufjwwoRwJiZ6NjFj/xXQUUdw=
  api_key:
    secure: ufJf9993qw6FclIyWaxtpx6wkJkP/h44vJ94lBlsAX20chpsodbK9TgJe7zcXBViDEwoy7rqLVyC5E6eLE58uUkb46bjs+4krhm9tDGaXzp+MW2rW4t+xNMgePUBw4RKcDbrWNXDjR5TBJySkFxFXcXm9PacdOoy8Tk78P4fNklXUH6vvYfGtFG9e5varxzQpYhKX/1ORh0WGslcWCq9a23NQuwHMuuM+2N4jbicFqpjY/kNj9jo7qGDChRIaIiHkfXFZFuGb5+iHxQJBSbSB3s6e6wT6BYXgnslFryLTEZ4GxNSQAZWmlpaM6RzgUQswT7g7i/0UzywUn5DB+7JVzDtxsRdeFFNDS48npU1mWw6WmNIRVP8vhYk9cn/F49nqkKgNJhPVs4VjVeTjV9V8a5OLNKL7G9iNUWaSgQ8rPcvhOv+kpCKezBOsImiNJYOY3qEt99hZjliFaUoLAz99pJkreR6xxDpTXL8XFPVnAGtf/mboK4OS/HHR28vMh5Kd7mxFNsrdRbdDMNOl8lfYtVQdmQHtd/fZw+N5C0GHHKw/DTO8YVOmyXbKN4Aon2rq1/6wuUOW4FpzpA6qyNSFU94BgknNTzxyhpHaPZhG8vbU/m+54kMb2vfN67Yv0F751xTUtdRYnb8f5I4haN09rAGDKCyOufWNkvtyqNWf+Q=
  on:
    tags: true
    repo: ajulienne/tartiflette
