language: node_js

node_js:
  - node

install:
  - npm install -g codecov

script:
  - npm run build
  - npm run test

deploy:
  - provider: npm
    edge: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    on:
      tags: true
      repo: ajulienne/tartiflette
